# Generated by Django 4.2.1 on 2023-07-26 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_alter_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user_en_us',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='user_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(default='местные новости', help_text='category name', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='местные новости', help_text='category name', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers_en_us',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers_ru',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='contents_en_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contents_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='header_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='header_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_tip_en_us',
            field=models.CharField(choices=[('NW', 'Новость'), ('PS', 'Статья')], default='PS', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_tip_ru',
            field=models.CharField(choices=[('NW', 'Новость'), ('PS', 'Статья')], default='PS', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='местные новости', help_text='category name', max_length=20),
        ),
    ]
