# Generated by Django 4.2.1 on 2023-07-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_author_user_en_us_author_user_ru_category_name_en_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers_en_us',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers_ru',
        ),
    ]
